env ACTIVE_COLOR;

events {}

http {
    # valeur par défaut si la variable est vide
    map $ACTIVE_COLOR $active_color {
        default "blue";
        "blue"  "blue";
        "green" "green";
    }

    upstream backend_blue {
        server backend-blue:3000;
    }

    upstream backend_green {
        server backend-green:3000;
    }

    map $active_color $target_upstream {
        default backend_blue;
        "blue"  backend_blue;
        "green" backend_green;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$target_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
