env ACTIVE_COLOR;

events {}

http {
    map $ACTIVE_COLOR $active_color {
        default "blue";
        "blue"  "blue";
        "green" "green";
    }

    upstream frontend_blue {
        server frontend-blue:80;
    }

    upstream frontend_green {
        server frontend-green:80;
    }

    map $active_color $target_frontend {
        default frontend_blue;
        "blue"  frontend_blue;
        "green" frontend_green;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend-green:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://$target_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
